from django.urls import path
from. import views
urlpatterns = [
    path('', views.index, name='index'),
    path('aboutus',views.aboutus, name='aboutus'),
    path('login',views.login, name='login'),
    path('signup', views.signup, name='signup'),
    path('verify-otp/', views.verify_otp, name='verify_otp'),
    path('user/',views.user_dashboard, name='user_dashboard'),
    path('admin/',views.admin_dashboard, name='admin_dashboard'),
    path('diabetes-risk/',views.diabetes_risk, name='diabetes_risk'),
    path('heart-risk/',views.heart_risk, name='heart_risk'),
    path('liver-risk/',views.liver_risk,name='liver_risk'),
    path('thyroid-risk/',views.thyroid_risk,name='thyroid_risk'),
    path('logout/',views.logout,name='logout'),
    path('feedback/',views.feedback,name='feedback'),
    path('report-issue/',views.report_issue,name='report_issue'),
    path('predict_diabetes/', views.predict_diabetes, name='predict_diabetes'),
    path('predict_heart/', views.predict_heart, name='predict_heart'),
    path('predict_liver/', views.predict_liver, name='predict_liver'),
    path('predict_thyroid/', views.predict_thyroid, name='predict_thyroid'),
    path('download_diabetes_report/<int:dr_id>/', views.download_diabetes_report, name='download_diabetes_report'),
    path('download_heart_report/<int:hr_id>/', views.download_heart_report, name='download_heart_report'),
    path('download_liver_report/<int:lr_id>/', views.download_liver_report, name='download_liver_report'),
    path('download_thyroid_report/<int:tr_id>/', views.download_thyroid_report, name='download_thyroid_report'),
    path('history/', views.history_view, name='history'),
]
